[experiment]
targets = ["Count_EX1", "Count_EX2"]
study_name = "bin_base_eq_width_3"
objective = "reg:squarederror"

[data]
directory = "data/raw/Organized_Data"
discard_features = []
onehot_encoding = true
sen_geometrical = false
clogging_factors = false
lagged_features = []
feature_lag_amount = 0
mould_position = false
remove_rows = 0
include_subdirs = []
exclude_subdirs = []

[tune]
study_count = 100
tree_method = "hist"
storage_path = "sqlite:///optuna/experiments_binning.db"
multithread = false

[train]
subsample_shap = false
config_file = ""

[predict]
config_file = "config/training_config_bin_base_eq_width_3.json"
data_directory = "New_Data"
piv_data = false

[wandb]
project = "steel-flow"
entity = ""
enabled = true

[bins]
enabled = true
n_bins = 3
strategy = "equal_width"
